services:
  - type: web
    name: library-safety-backend
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false  
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.7"